create table if not exists public.quote_item_area_allocations (
  id bigint generated by default as identity primary key,
  quote_item_id bigint not null references public.quote_items(id) on delete cascade,
  area text not null,
  quantity numeric not null,
  supply_type text not null,
  customer_visible_note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quote_item_area_allocations_quantity_positive check (quantity > 0),
  constraint quote_item_area_allocations_supply_type_check
    check (supply_type in ('new_equipment', 'client_existing'))
);

create index if not exists quote_item_area_allocations_quote_item_id_idx
  on public.quote_item_area_allocations (quote_item_id);

create index if not exists quote_item_area_allocations_quote_item_sort_idx
  on public.quote_item_area_allocations (quote_item_id, sort_order);

comment on table public.quote_item_area_allocations
  is 'Customer-visible area and supply-type distribution for quote item quantities.';

comment on column public.quote_item_area_allocations.supply_type
  is 'new_equipment charges equipment proportionally; client_existing charges equipment as zero while preserving labor.';

drop trigger if exists set_quote_item_area_allocations_updated_at
  on public.quote_item_area_allocations;

create trigger set_quote_item_area_allocations_updated_at
before update on public.quote_item_area_allocations
for each row execute function public.set_updated_at();

alter table public.quote_item_area_allocations enable row level security;

drop policy if exists beta_authenticated_select
  on public.quote_item_area_allocations;
drop policy if exists beta_authenticated_insert
  on public.quote_item_area_allocations;
drop policy if exists beta_authenticated_update
  on public.quote_item_area_allocations;
drop policy if exists beta_authenticated_delete
  on public.quote_item_area_allocations;

create policy beta_authenticated_select
on public.quote_item_area_allocations
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.quote_item_area_allocations
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.quote_item_area_allocations
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.quote_item_area_allocations
for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
