create table if not exists public.project_site_visit_note_photos (
  id bigint generated by default as identity primary key,
  project_site_visit_note_id bigint not null references public.project_site_visit_notes(id) on delete cascade,
  image_url text not null,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists project_site_visit_note_photos_note_id_idx
  on public.project_site_visit_note_photos(project_site_visit_note_id);

alter table public.project_site_visit_note_photos enable row level security;

drop policy if exists beta_authenticated_select on public.project_site_visit_note_photos;
drop policy if exists beta_authenticated_insert on public.project_site_visit_note_photos;
drop policy if exists beta_authenticated_update on public.project_site_visit_note_photos;
drop policy if exists beta_authenticated_delete on public.project_site_visit_note_photos;

create policy beta_authenticated_select
on public.project_site_visit_note_photos
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_site_visit_note_photos
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_site_visit_note_photos
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_site_visit_note_photos
for delete
to authenticated
using (true);
