-- El Vigia - Sprint B2: "Investigar a fondo" un hallazgo bajo demanda.
--
-- Cada investigacion:
--   1. Un playbook determinista arma un expediente (dossier) con consultas SQL
--      de diagnostico sobre las tablas de negocio (solo lectura).
--   2. Una unica llamada a Claude interpreta el expediente y propone la causa
--      raiz + accion recomendada (structured output).
--   3. El diagnostico se guarda aqui y se manda por correo aparte.
--
-- Candado de costo: tope mensual en USD (VIGIA_INVESTIGATE_MONTHLY_CAP_USD,
-- default 25). Al alcanzarlo, el status queda 'sin_presupuesto' y no se llama
-- al modelo. El gasto del mes se calcula sumando cost_usd de las filas del mes.
--
-- Aditivo: tabla nueva + policy de solo lectura. Aplicado a prod 2026-09-01.

create table if not exists public.vigia_investigations (
  id bigint generated by default as identity primary key,
  finding_id bigint references public.vigia_findings(id) on delete set null,
  sensor_id text,
  entity_type text,
  entity_id text,
  trigger text not null default 'manual' check (trigger in ('manual', 'auto_critico')),
  status text not null default 'running'
    check (status in ('running', 'completada', 'error', 'sin_presupuesto')),
  playbook text,
  dossier jsonb,
  interpretation jsonb,
  model text,
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(10,4) not null default 0,
  error text,
  requested_by text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists vigia_investigations_finding_idx
  on public.vigia_investigations (finding_id);
create index if not exists vigia_investigations_started_idx
  on public.vigia_investigations (started_at desc);

alter table public.vigia_investigations enable row level security;

drop policy if exists vigia_authenticated_select on public.vigia_investigations;
create policy vigia_authenticated_select on public.vigia_investigations
  for select to authenticated using (true);

notify pgrst, 'reload schema';
