create table if not exists public.project_payment_complements (
  id bigint generated by default as identity primary key,
  project_invoice_id bigint not null references public.project_invoices(id) on delete cascade,
  project_payment_id bigint references public.project_payments(id) on delete set null,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  status text not null default 'draft',
  complement_env text not null default 'sandbox',
  partiality_number integer not null check (partiality_number > 0),
  previous_balance_mxn numeric(14,2) not null check (previous_balance_mxn >= 0),
  amount_paid_mxn numeric(14,2) not null check (amount_paid_mxn > 0),
  outstanding_balance_mxn numeric(14,2) not null check (outstanding_balance_mxn >= 0),
  payment_date date not null,
  payment_form_code text not null references public.sat_payment_form_catalog(code),
  currency text not null default 'MXN' check (currency in ('MXN')),
  exchange_rate numeric(14,6),
  payment_reference text,
  payload_preview jsonb not null,
  facturama_id text,
  sat_uuid text,
  facturama_response jsonb,
  last_error text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_payment_complements_status_check
    check (status in ('draft', 'validated', 'stamped', 'cancelled', 'failed')),
  constraint project_payment_complements_env_check
    check (complement_env in ('sandbox', 'production')),
  constraint project_payment_complements_balance_check
    check (round((previous_balance_mxn - amount_paid_mxn)::numeric, 2) = outstanding_balance_mxn)
);

alter table public.project_payment_complements
  add column if not exists project_invoice_id bigint references public.project_invoices(id) on delete cascade,
  add column if not exists project_payment_id bigint references public.project_payments(id) on delete set null,
  add column if not exists client_project_id bigint references public.client_projects(id) on delete cascade,
  add column if not exists client_id bigint references public.clients(id) on delete cascade,
  add column if not exists status text default 'draft',
  add column if not exists complement_env text default 'sandbox',
  add column if not exists partiality_number integer,
  add column if not exists previous_balance_mxn numeric(14,2),
  add column if not exists amount_paid_mxn numeric(14,2),
  add column if not exists outstanding_balance_mxn numeric(14,2),
  add column if not exists payment_date date,
  add column if not exists payment_form_code text references public.sat_payment_form_catalog(code),
  add column if not exists currency text default 'MXN',
  add column if not exists exchange_rate numeric(14,6),
  add column if not exists payment_reference text,
  add column if not exists payload_preview jsonb,
  add column if not exists facturama_id text,
  add column if not exists sat_uuid text,
  add column if not exists facturama_response jsonb,
  add column if not exists last_error text,
  add column if not exists created_by_user_id uuid references auth.users(id),
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create index if not exists project_payment_complements_invoice_idx
  on public.project_payment_complements(project_invoice_id);

create index if not exists project_payment_complements_payment_idx
  on public.project_payment_complements(project_payment_id);

create index if not exists project_payment_complements_project_idx
  on public.project_payment_complements(client_project_id);

create index if not exists project_payment_complements_status_idx
  on public.project_payment_complements(status);

create unique index if not exists project_payment_complements_payment_active_uidx
  on public.project_payment_complements(project_payment_id)
  where project_payment_id is not null
    and status in ('draft', 'validated', 'stamped');

alter table public.project_payment_complements enable row level security;

drop policy if exists beta_authenticated_select on public.project_payment_complements;
drop policy if exists beta_authenticated_insert on public.project_payment_complements;
drop policy if exists beta_authenticated_update on public.project_payment_complements;
drop policy if exists beta_authenticated_delete on public.project_payment_complements;

create policy beta_authenticated_select
on public.project_payment_complements
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_payment_complements
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_payment_complements
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_payment_complements
for delete
to authenticated
using (true);
