create table if not exists public.contractors (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  specialty text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contractor_account_movements (
  id bigint generated by default as identity primary key,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  client_project_id bigint references public.client_projects(id) on delete set null,
  work_order_id bigint references public.work_orders(id) on delete set null,
  movement_date date not null default current_date,
  movement_type text not null
    check (movement_type in ('advance_payment', 'work_charge', 'adjustment', 'refund')),
  amount_mxn numeric(14,2) not null,
  description text,
  payment_method text,
  reference text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists contractors_is_active_idx
  on public.contractors(is_active);

create index if not exists contractor_account_movements_contractor_id_idx
  on public.contractor_account_movements(contractor_id);

create index if not exists contractor_account_movements_project_id_idx
  on public.contractor_account_movements(client_project_id);

create index if not exists contractor_account_movements_work_order_id_idx
  on public.contractor_account_movements(work_order_id);

create index if not exists contractor_account_movements_date_idx
  on public.contractor_account_movements(movement_date);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'work_orders'
  ) then
    alter table public.work_orders
      add column if not exists contractor_id bigint references public.contractors(id) on delete set null,
      add column if not exists contractor_amount_mxn numeric(14,2) not null default 0,
      add column if not exists contractor_payment_status text not null default 'pending';

    alter table public.work_orders
      drop constraint if exists work_orders_contractor_payment_status_check;

    alter table public.work_orders
      add constraint work_orders_contractor_payment_status_check
      check (contractor_payment_status in (
        'pending',
        'applied_to_balance',
        'paid_direct',
        'cancelled'
      ));

    create index if not exists work_orders_contractor_id_idx
      on public.work_orders(contractor_id);

    create index if not exists work_orders_contractor_payment_status_idx
      on public.work_orders(contractor_payment_status);
  end if;
end $$;

alter table public.contractors enable row level security;
alter table public.contractor_account_movements enable row level security;

drop policy if exists beta_authenticated_select on public.contractors;
drop policy if exists beta_authenticated_insert on public.contractors;
drop policy if exists beta_authenticated_update on public.contractors;
drop policy if exists beta_authenticated_delete on public.contractors;

create policy beta_authenticated_select
on public.contractors
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.contractors
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.contractors
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.contractors
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.contractor_account_movements;
drop policy if exists beta_authenticated_insert on public.contractor_account_movements;
drop policy if exists beta_authenticated_update on public.contractor_account_movements;
drop policy if exists beta_authenticated_delete on public.contractor_account_movements;

create policy beta_authenticated_select
on public.contractor_account_movements
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.contractor_account_movements
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.contractor_account_movements
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.contractor_account_movements
for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
