create table if not exists public.service_reports (
  id bigint generated by default as identity primary key,
  service_number text unique,
  client_id bigint references public.clients(id) on delete set null,
  client_project_id bigint references public.client_projects(id) on delete set null,
  service_location text,
  google_maps_url text,
  performed_by_name text,
  service_date date not null default current_date,
  background text,
  diagnosis text,
  solution_status text not null default 'pending'
    check (solution_status in ('solved', 'not_solved', 'pending')),
  solution_description text,
  requires_parts boolean not null default false,
  required_parts_notes text,
  technician_cost_mxn numeric(14,2) not null default 0,
  labor_sale_mxn numeric(14,2) not null default 0,
  status text not null default 'draft'
    check (status in ('draft', 'pending', 'completed', 'cancelled')),
  related_quote_id bigint references public.quotes(id) on delete set null,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_report_photos (
  id bigint generated by default as identity primary key,
  service_report_id bigint not null references public.service_reports(id) on delete cascade,
  image_url text not null,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists service_reports_client_id_idx
  on public.service_reports(client_id);

create index if not exists service_reports_project_id_idx
  on public.service_reports(client_project_id);

create index if not exists service_reports_service_date_idx
  on public.service_reports(service_date);

create index if not exists service_reports_status_idx
  on public.service_reports(status);

create index if not exists service_report_photos_report_id_idx
  on public.service_report_photos(service_report_id);

alter table public.service_reports enable row level security;
alter table public.service_report_photos enable row level security;

drop policy if exists beta_authenticated_select on public.service_reports;
drop policy if exists beta_authenticated_insert on public.service_reports;
drop policy if exists beta_authenticated_update on public.service_reports;
drop policy if exists beta_authenticated_delete on public.service_reports;

create policy beta_authenticated_select
on public.service_reports
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.service_reports
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.service_reports
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.service_reports
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.service_report_photos;
drop policy if exists beta_authenticated_insert on public.service_report_photos;
drop policy if exists beta_authenticated_update on public.service_report_photos;
drop policy if exists beta_authenticated_delete on public.service_report_photos;

create policy beta_authenticated_select
on public.service_report_photos
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.service_report_photos
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.service_report_photos
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.service_report_photos
for delete
to authenticated
using (true);
