-- Sprint G4 - Voz/texto -> intencion -> borrador de cotizacion
--
-- Leo dicta desde el coche ("cotizacion para Guillermo de 4 camaras Hikvision
-- y un NVR de 8 canales"). Un agente (1 loop de herramientas sobre Claude)
-- resuelve cliente + productos + plantillas y crea un borrador via
-- lib/quotes/draftBuilder.ts. El borrador SIEMPRE se abre para revision;
-- nunca se envia al cliente ni se timbra.
--
-- Esta tabla registra cada intento: transcripcion, herramientas llamadas,
-- costo, y el resultado (borrador creado, pregunta de aclaracion, o error).
-- Candado de costo mensual: QUOTE_VOICE_MONTHLY_CAP_USD (default 15).
--
-- Aditivo: 1 tabla nueva + RLS select-only.

create table if not exists public.quote_voice_drafts (
  id bigint generated by default as identity primary key,
  transcript text not null,
  actor text not null default 'voz',
  status text not null default 'running'
    check (status in ('running', 'completada', 'aclaracion', 'error', 'sin_presupuesto')),
  result_quote_id bigint references public.quotes(id) on delete set null,
  clarification_question text,
  assumptions jsonb,
  tool_calls jsonb,
  model text,
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(10,4) not null default 0,
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists quote_voice_drafts_started_idx
  on public.quote_voice_drafts (started_at desc);

alter table public.quote_voice_drafts enable row level security;

drop policy if exists quote_voice_drafts_authenticated_select on public.quote_voice_drafts;
create policy quote_voice_drafts_authenticated_select on public.quote_voice_drafts
  for select to authenticated using (true);

notify pgrst, 'reload schema';
