create table if not exists public.notification_recipients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  channel text not null default 'whatsapp',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  client_project_id bigint references public.client_projects(id),
  title text,
  message text,
  status text not null default 'pending',
  provider_response jsonb,
  created_at timestamptz not null default now()
);

create index if not exists notification_recipients_active_idx
  on public.notification_recipients(is_active, channel);

create index if not exists notification_events_project_idx
  on public.notification_events(client_project_id);

create index if not exists notification_events_type_idx
  on public.notification_events(event_type);

alter table public.notification_recipients enable row level security;
alter table public.notification_events enable row level security;

drop policy if exists beta_authenticated_select on public.notification_recipients;
drop policy if exists beta_authenticated_insert on public.notification_recipients;
drop policy if exists beta_authenticated_update on public.notification_recipients;
drop policy if exists beta_authenticated_delete on public.notification_recipients;

create policy beta_authenticated_select
on public.notification_recipients
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.notification_recipients
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.notification_recipients
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.notification_recipients
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.notification_events;
drop policy if exists beta_authenticated_insert on public.notification_events;
drop policy if exists beta_authenticated_update on public.notification_events;
drop policy if exists beta_authenticated_delete on public.notification_events;

create policy beta_authenticated_select
on public.notification_events
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.notification_events
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.notification_events
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.notification_events
for delete
to authenticated
using (true);
