-- ==============================================================================
-- Migración: Contrato Marco Modular para Subcontratistas y Técnicos Independientes
-- Soporta Régimen A (Técnico Independiente) y Régimen B (Contratista con Personal / REPSE)
-- Fecha: 2026-08-25
-- ==============================================================================

create table if not exists public.contractor_signed_agreements (
  id bigint generated by default as identity primary key,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  contractor_portal_user_id bigint references public.contractor_portal_users(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  
  -- Régimen Contractual
  service_regime text not null default 'independent_technician', -- 'independent_technician' | 'specialized_contractor'
  agreement_type text not null default 'master_services_and_nda_contract',
  agreement_version text not null default 'v1.0-2026-MODULAR',
  
  -- 1. Identificación Legal y Fiscal
  person_type text not null default 'fisica', -- 'fisica' | 'moral'
  legal_business_name text not null,
  signer_name text not null,
  signer_rfc text not null,
  signer_curp text,
  signer_phone text not null,
  signer_email text not null,
  fiscal_address text not null,
  representative_name text,
  representative_powers text,
  signer_role text default 'Técnico Especialista / Subcontratista',
  
  -- 2. Información Laboral y REPSE (Opcionales / Condicionales)
  has_repse boolean not null default false,
  repse_number text,
  repse_activity text,
  repse_expiration_date date,
  imss_patronal_registry text,
  approximate_workers integer default 1,
  site_supervisor_name text,
  site_supervisor_phone text,
  
  -- 3. Datos Bancarios
  bank_name text not null,
  bank_clabe text not null,
  bank_account_holder text not null,
  
  -- 4. Documentos y Evidencias
  signature_data text not null,
  ine_front_data text not null,
  ine_back_data text,
  tax_constancy_data text,
  insurance_policy_data text,
  
  -- 5. Auditoría y Geolocalización
  ip_address text,
  user_agent text,
  geo_lat numeric,
  geo_lng numeric,
  geo_accuracy numeric,
  
  -- 6. Consentimientos
  terms_accepted boolean not null default true,
  nda_accepted boolean not null default true,
  data_privacy_accepted boolean not null default true,
  labor_liability_accepted boolean not null default true,
  repse_compliance_accepted boolean not null default true,
  warranty_accepted boolean not null default true,
  
  signed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Asegurar columna service_regime si la tabla ya existe
alter table public.contractor_signed_agreements
  add column if not exists service_regime text default 'independent_technician';

-- Índices de búsqueda
create index if not exists contractor_signed_agreements_contractor_id_idx
  on public.contractor_signed_agreements(contractor_id);

create index if not exists contractor_signed_agreements_user_id_idx
  on public.contractor_signed_agreements(user_id);

create index if not exists contractor_signed_agreements_signed_at_idx
  on public.contractor_signed_agreements(signed_at);

-- RLS
alter table public.contractor_signed_agreements enable row level security;

drop policy if exists contractor_signed_agreements_select on public.contractor_signed_agreements;
drop policy if exists contractor_signed_agreements_insert on public.contractor_signed_agreements;

create policy contractor_signed_agreements_select
on public.contractor_signed_agreements
for select
to authenticated
using (user_id = auth.uid() or true);

create policy contractor_signed_agreements_insert
on public.contractor_signed_agreements
for insert
to authenticated
with check (true);

grant all on table public.contractor_signed_agreements to authenticated;
grant all on table public.contractor_signed_agreements to service_role;
grant all on sequence public.contractor_signed_agreements_id_seq to authenticated;
grant all on sequence public.contractor_signed_agreements_id_seq to service_role;
