-- ==============================================================================
-- Migración Completa: Portal de Subcontratistas, Convenios Legales y Perfiles
-- Fecha: 2026-08-25
-- ==============================================================================

-- 1. Actualizar restricciones en profiles para soportar usuarios contratistas
alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
  check (role in (
    'admin',
    'direccion',
    'comercial',
    'ingenieria',
    'project_manager',
    'instalador',
    'compras',
    'finanzas',
    'client',
    'contractor'
  ));

alter table public.profiles
  drop constraint if exists profiles_user_type_check;

alter table public.profiles
  add constraint profiles_user_type_check
  check (user_type in ('internal', 'client_portal', 'contractor_portal'));

-- 2. Tabla para vinculación de usuarios con contratistas
create table if not exists public.contractor_portal_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  is_active boolean not null default true,
  invited_at timestamptz,
  invitation_status text not null default 'pending'
    check (invitation_status in ('pending', 'sent', 'existing_user', 'error')),
  invitation_error text,
  created_at timestamptz not null default now(),
  constraint contractor_portal_users_user_id_contractor_id_key unique (user_id, contractor_id)
);

create index if not exists contractor_portal_users_user_id_idx
  on public.contractor_portal_users(user_id);

create index if not exists contractor_portal_users_contractor_id_idx
  on public.contractor_portal_users(contractor_id);

create index if not exists contractor_portal_users_is_active_idx
  on public.contractor_portal_users(is_active);

-- 3. Tabla para registro de contratos marco firmados (29 cláusulas)
create table if not exists public.contractor_signed_agreements (
  id bigint generated by default as identity primary key,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  contractor_portal_user_id bigint references public.contractor_portal_users(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  
  -- Régimen y Versión
  service_regime text not null default 'independent_technician', -- 'independent_technician' | 'specialized_contractor'
  agreement_type text not null default 'master_services_and_nda_contract',
  agreement_version text not null default 'v1.0-2026-MODULAR',
  
  -- 1. Identificación Legal y Fiscal
  person_type text not null default 'fisica', -- 'fisica' | 'moral'
  legal_business_name text not null,
  signer_name text not null,
  signer_rfc text not null,
  signer_curp text,
  signer_phone text not null,
  signer_email text not null,
  fiscal_address text not null,
  representative_name text,
  representative_powers text,
  signer_role text default 'Técnico Especialista / Subcontratista',
  
  -- 2. Información Laboral y REPSE (Opcionales)
  has_repse boolean not null default false,
  repse_number text,
  repse_activity text,
  repse_expiration_date date,
  imss_patronal_registry text,
  approximate_workers integer default 1,
  site_supervisor_name text,
  site_supervisor_phone text,
  
  -- 3. Datos Bancarios
  bank_name text not null,
  bank_clabe text not null,
  bank_account_holder text not null,
  
  -- 4. Documentos y Evidencias
  signature_data text not null,
  ine_front_data text not null,
  ine_back_data text,
  tax_constancy_data text,
  insurance_policy_data text,
  
  -- 5. Auditoría y Geolocalización
  ip_address text,
  user_agent text,
  geo_lat numeric,
  geo_lng numeric,
  geo_accuracy numeric,
  
  -- 6. Consentimientos
  terms_accepted boolean not null default true,
  nda_accepted boolean not null default true,
  data_privacy_accepted boolean not null default true,
  labor_liability_accepted boolean not null default true,
  repse_compliance_accepted boolean not null default true,
  warranty_accepted boolean not null default true,
  
  signed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Asegurar columnas si ya existía
alter table public.contractor_signed_agreements
  add column if not exists service_regime text default 'independent_technician',
  add column if not exists person_type text default 'fisica',
  add column if not exists legal_business_name text,
  add column if not exists signer_email text,
  add column if not exists fiscal_address text,
  add column if not exists representative_name text,
  add column if not exists representative_powers text,
  add column if not exists has_repse boolean default false,
  add column if not exists repse_number text,
  add column if not exists repse_activity text,
  add column if not exists repse_expiration_date date,
  add column if not exists imss_patronal_registry text,
  add column if not exists approximate_workers integer default 1,
  add column if not exists site_supervisor_name text,
  add column if not exists site_supervisor_phone text,
  add column if not exists bank_name text,
  add column if not exists bank_clabe text,
  add column if not exists bank_account_holder text,
  add column if not exists tax_constancy_data text,
  add column if not exists insurance_policy_data text;

create index if not exists contractor_signed_agreements_contractor_id_idx
  on public.contractor_signed_agreements(contractor_id);

create index if not exists contractor_signed_agreements_user_id_idx
  on public.contractor_signed_agreements(user_id);

create index if not exists contractor_signed_agreements_signed_at_idx
  on public.contractor_signed_agreements(signed_at);

-- 4. Columna contractor_id en service_reports
do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'service_reports'
  ) then
    alter table public.service_reports
      add column if not exists contractor_id bigint references public.contractors(id) on delete set null;

    create index if not exists service_reports_contractor_id_idx
      on public.service_reports(contractor_id);
  end if;
end $$;

-- 5. Row Level Security (RLS) y Permisos
alter table public.contractor_portal_users enable row level security;
alter table public.contractor_signed_agreements enable row level security;

drop policy if exists contractor_portal_users_select_self on public.contractor_portal_users;
drop policy if exists contractor_portal_users_admin_all on public.contractor_portal_users;

create policy contractor_portal_users_select_self
on public.contractor_portal_users
for select
to authenticated
using (user_id = auth.uid());

create policy contractor_portal_users_admin_all
on public.contractor_portal_users
for all
to authenticated
using (true)
with check (true);

drop policy if exists contractor_signed_agreements_select on public.contractor_signed_agreements;
drop policy if exists contractor_signed_agreements_insert on public.contractor_signed_agreements;

create policy contractor_signed_agreements_select
on public.contractor_signed_agreements
for select
to authenticated
using (user_id = auth.uid() or true);

create policy contractor_signed_agreements_insert
on public.contractor_signed_agreements
for insert
to authenticated
with check (true);

grant all on table public.contractor_portal_users to authenticated;
grant all on table public.contractor_portal_users to service_role;
grant all on sequence public.contractor_portal_users_id_seq to authenticated;
grant all on sequence public.contractor_portal_users_id_seq to service_role;

grant all on table public.contractor_signed_agreements to authenticated;
grant all on table public.contractor_signed_agreements to service_role;
grant all on sequence public.contractor_signed_agreements_id_seq to authenticated;
grant all on sequence public.contractor_signed_agreements_id_seq to service_role;
