create table if not exists public.project_payment_complements (
  id bigint generated by default as identity primary key,
  project_invoice_id bigint not null references public.project_invoices(id) on delete cascade,
  project_payment_id bigint references public.project_payments(id) on delete set null,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  status text not null default 'draft',
  complement_env text not null default 'sandbox',
  partiality_number integer not null check (partiality_number > 0),
  previous_balance_mxn numeric(14,2) not null check (previous_balance_mxn >= 0),
  amount_paid_mxn numeric(14,2) not null check (amount_paid_mxn > 0),
  paid_amount_mxn numeric(14,2) not null check (paid_amount_mxn > 0),
  source_payment_amount_mxn numeric(14,2),
  manual_amount_override boolean not null default false,
  manual_override_reason text,
  outstanding_balance_mxn numeric(14,2) not null check (outstanding_balance_mxn >= 0),
  payment_date date not null,
  payment_form_code text not null references public.sat_payment_form_catalog(code),
  currency text not null default 'MXN' check (currency in ('MXN')),
  exchange_rate numeric(14,6),
  payment_reference text,
  payload_preview jsonb not null,
  pdf_url text,
  xml_url text,
  facturama_id text,
  sat_uuid text,
  facturama_response jsonb,
  last_error text,
  created_by_user_id uuid references auth.users(id),
  issued_by_user_id uuid references auth.users(id),
  issued_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_payment_complements_status_check
    check (status in ('draft', 'validated', 'issued', 'stamped', 'cancelled', 'failed')),
  constraint project_payment_complements_env_check
    check (complement_env in ('sandbox', 'production')),
  constraint project_payment_complements_balance_check
    check (round((previous_balance_mxn - paid_amount_mxn)::numeric, 2) = outstanding_balance_mxn),
  constraint project_payment_complements_override_reason_check
    check (manual_amount_override = false or nullif(trim(coalesce(manual_override_reason, '')), '') is not null)
);

alter table public.project_payment_complements
  add column if not exists project_invoice_id bigint references public.project_invoices(id) on delete cascade,
  add column if not exists project_payment_id bigint references public.project_payments(id) on delete set null,
  add column if not exists client_project_id bigint references public.client_projects(id) on delete cascade,
  add column if not exists client_id bigint references public.clients(id) on delete cascade,
  add column if not exists status text default 'draft',
  add column if not exists complement_env text default 'sandbox',
  add column if not exists partiality_number integer,
  add column if not exists previous_balance_mxn numeric(14,2),
  add column if not exists amount_paid_mxn numeric(14,2),
  add column if not exists paid_amount_mxn numeric(14,2),
  add column if not exists source_payment_amount_mxn numeric(14,2),
  add column if not exists manual_amount_override boolean default false,
  add column if not exists manual_override_reason text,
  add column if not exists outstanding_balance_mxn numeric(14,2),
  add column if not exists payment_date date,
  add column if not exists payment_form_code text references public.sat_payment_form_catalog(code),
  add column if not exists currency text default 'MXN',
  add column if not exists exchange_rate numeric(14,6),
  add column if not exists payment_reference text,
  add column if not exists payload_preview jsonb,
  add column if not exists pdf_url text,
  add column if not exists xml_url text,
  add column if not exists facturama_id text,
  add column if not exists sat_uuid text,
  add column if not exists facturama_response jsonb,
  add column if not exists last_error text,
  add column if not exists created_by_user_id uuid references auth.users(id),
  add column if not exists issued_by_user_id uuid references auth.users(id),
  add column if not exists issued_at timestamptz,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.project_payment_complements
set issued_at = coalesce(issued_at, updated_at, created_at),
    issued_by_user_id = coalesce(issued_by_user_id, created_by_user_id)
where status in ('issued', 'stamped')
  and (issued_at is null or issued_by_user_id is null);

update public.project_payment_complements
set paid_amount_mxn = coalesce(paid_amount_mxn, amount_paid_mxn),
    amount_paid_mxn = coalesce(amount_paid_mxn, paid_amount_mxn),
    manual_amount_override = coalesce(manual_amount_override, false)
where paid_amount_mxn is null
   or amount_paid_mxn is null
   or manual_amount_override is null;

alter table public.project_payment_complements
  alter column paid_amount_mxn set not null,
  alter column amount_paid_mxn set not null,
  alter column manual_amount_override set not null;

alter table public.project_payment_complements
  drop constraint if exists project_payment_complements_balance_check,
  drop constraint if exists project_payment_complements_override_reason_check,
  drop constraint if exists project_payment_complements_status_check;

alter table public.project_payment_complements
  add constraint project_payment_complements_status_check
    check (status in ('draft', 'validated', 'issued', 'stamped', 'cancelled', 'failed')),
  add constraint project_payment_complements_balance_check
    check (round((previous_balance_mxn - paid_amount_mxn)::numeric, 2) = outstanding_balance_mxn),
  add constraint project_payment_complements_override_reason_check
    check (manual_amount_override = false or nullif(trim(coalesce(manual_override_reason, '')), '') is not null);

create index if not exists project_payment_complements_invoice_idx
  on public.project_payment_complements(project_invoice_id);

create index if not exists project_payment_complements_payment_idx
  on public.project_payment_complements(project_payment_id);

create index if not exists project_payment_complements_project_idx
  on public.project_payment_complements(client_project_id);

create index if not exists project_payment_complements_status_idx
  on public.project_payment_complements(status);

create index if not exists project_payment_complements_issued_at_idx
  on public.project_payment_complements(project_invoice_id, issued_at)
  where status in ('issued', 'stamped');

drop index if exists public.project_payment_complements_payment_active_uidx;

create unique index if not exists project_payment_complements_payment_stamped_uidx
  on public.project_payment_complements(project_payment_id)
  where project_payment_id is not null
    and status in ('issued', 'stamped');

alter table public.project_payment_complements enable row level security;

drop policy if exists beta_authenticated_select on public.project_payment_complements;
drop policy if exists beta_authenticated_insert on public.project_payment_complements;
drop policy if exists beta_authenticated_update on public.project_payment_complements;
drop policy if exists beta_authenticated_delete on public.project_payment_complements;

create policy beta_authenticated_select
on public.project_payment_complements
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_payment_complements
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_payment_complements
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_payment_complements
for delete
to authenticated
using (true);

alter table public.project_payments
  add column if not exists payment_form_code text references public.sat_payment_form_catalog(code),
  add column if not exists updated_at timestamptz default now();

create table if not exists public.project_payment_audit_log (
  id bigint generated by default as identity primary key,
  project_payment_id bigint not null references public.project_payments(id) on delete cascade,
  changed_by_user_id uuid references auth.users(id),
  old_values jsonb not null,
  new_values jsonb not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists project_payment_audit_log_payment_idx
  on public.project_payment_audit_log(project_payment_id);

create index if not exists project_payment_audit_log_created_idx
  on public.project_payment_audit_log(created_at);

alter table public.project_payment_audit_log enable row level security;

drop policy if exists beta_authenticated_select on public.project_payment_audit_log;
drop policy if exists beta_authenticated_insert on public.project_payment_audit_log;

create policy beta_authenticated_select
on public.project_payment_audit_log
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_payment_audit_log
for insert
to authenticated
with check (true);
