create table if not exists public.project_translation_changes (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  operational_item_id bigint references public.project_operational_items(id) on delete set null,
  change_type text not null
    check (change_type in ('substitute', 'quantity_change', 'add', 'delete')),
  old_product_name text,
  new_product_name text,
  old_quantity numeric(14,2),
  new_quantity numeric(14,2),
  old_unit_cost numeric(14,2),
  new_unit_cost numeric(14,2),
  cost_difference numeric(14,2) not null default 0,
  notes text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists project_translation_changes_project_id_idx
  on public.project_translation_changes(client_project_id);

create index if not exists project_translation_changes_operational_item_id_idx
  on public.project_translation_changes(operational_item_id);

create index if not exists project_translation_changes_created_at_idx
  on public.project_translation_changes(created_at);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'project_operational_items'
  ) then
    alter table public.project_operational_items
      drop constraint if exists project_operational_items_status_check;

    alter table public.project_operational_items
      add constraint project_operational_items_status_check
      check (status in (
        'draft',
        'active',
        'locked',
        'purchased',
        'partially_purchased',
        'delivered',
        'pending_director_approval'
      ));
  end if;
end $$;

alter table public.project_translation_changes enable row level security;

drop policy if exists beta_authenticated_select on public.project_translation_changes;
drop policy if exists beta_authenticated_insert on public.project_translation_changes;
drop policy if exists beta_authenticated_update on public.project_translation_changes;
drop policy if exists beta_authenticated_delete on public.project_translation_changes;

create policy beta_authenticated_select
on public.project_translation_changes
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_translation_changes
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_translation_changes
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_translation_changes
for delete
to authenticated
using (true);
