create table if not exists public.labor_activity_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  default_unit text not null default 'pieza',
  default_internal_cost_mxn numeric(14,2) not null default 0,
  default_sale_price_mxn numeric(14,2) not null default 0,
  category text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists labor_activity_catalog_name_key
on public.labor_activity_catalog(lower(name));

create table if not exists public.quote_item_labor_activities (
  id bigint generated by default as identity primary key,
  quote_item_id bigint not null references public.quote_items(id) on delete cascade,
  labor_activity_id bigint references public.labor_activity_catalog(id) on delete set null,
  name_snapshot text not null,
  quantity numeric(14,2) not null default 1,
  unit text not null default 'pieza',
  internal_unit_cost_mxn numeric(14,2) not null default 0,
  sale_unit_price_mxn numeric(14,2) not null default 0,
  internal_total_mxn numeric(14,2) not null default 0,
  sale_total_mxn numeric(14,2) not null default 0,
  assigned_role text,
  notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists quote_item_labor_activities_quote_item_id_idx
  on public.quote_item_labor_activities(quote_item_id);

create index if not exists quote_item_labor_activities_labor_activity_id_idx
  on public.quote_item_labor_activities(labor_activity_id);

insert into public.labor_activity_catalog (name, default_unit)
select activity.name, activity.default_unit
from (
  values
    ('Suministro', 'pieza'),
    ('Instalacion', 'pieza'),
    ('Cableado', 'pieza'),
    ('Configuracion', 'pieza'),
    ('Programacion', 'pieza'),
    ('Puesta en marcha', 'pieza'),
    ('Capacitacion', 'servicio'),
    ('Supervision', 'servicio'),
    ('Mano de obra general', 'pieza')
) as activity(name, default_unit)
where not exists (
  select 1
  from public.labor_activity_catalog existing
  where lower(existing.name) = lower(activity.name)
);

insert into public.quote_item_labor_activities (
  quote_item_id,
  labor_activity_id,
  name_snapshot,
  quantity,
  unit,
  internal_unit_cost_mxn,
  sale_unit_price_mxn,
  internal_total_mxn,
  sale_total_mxn,
  sort_order
)
select
  qi.id,
  lac.id,
  'Mano de obra general',
  coalesce(qi.quantity, 1),
  'pieza',
  0,
  coalesce(qi.unit_labor_price, 0),
  0,
  coalesce(qi.quantity, 1) * coalesce(qi.unit_labor_price, 0),
  0
from public.quote_items qi
join public.labor_activity_catalog lac
  on lower(lac.name) = lower('Mano de obra general')
where coalesce(qi.unit_labor_price, 0) > 0
  and not exists (
    select 1
    from public.quote_item_labor_activities qila
    where qila.quote_item_id = qi.id
  );

alter table public.labor_activity_catalog enable row level security;
alter table public.quote_item_labor_activities enable row level security;

drop policy if exists beta_authenticated_select on public.labor_activity_catalog;
drop policy if exists beta_authenticated_insert on public.labor_activity_catalog;
drop policy if exists beta_authenticated_update on public.labor_activity_catalog;
drop policy if exists beta_authenticated_delete on public.labor_activity_catalog;

create policy beta_authenticated_select
on public.labor_activity_catalog
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.labor_activity_catalog
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.labor_activity_catalog
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.labor_activity_catalog
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.quote_item_labor_activities;
drop policy if exists beta_authenticated_insert on public.quote_item_labor_activities;
drop policy if exists beta_authenticated_update on public.quote_item_labor_activities;
drop policy if exists beta_authenticated_delete on public.quote_item_labor_activities;

create policy beta_authenticated_select
on public.quote_item_labor_activities
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.quote_item_labor_activities
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.quote_item_labor_activities
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.quote_item_labor_activities
for delete
to authenticated
using (true);
