create table if not exists public.project_operational_item_labor_activities (
  id bigint generated by default as identity primary key,
  project_operational_item_id bigint not null references public.project_operational_items(id) on delete cascade,
  source_quote_item_labor_activity_id bigint references public.quote_item_labor_activities(id) on delete set null,
  labor_activity_id bigint references public.labor_activity_catalog(id) on delete set null,
  name_snapshot text not null,
  quantity numeric(14,2) not null default 1,
  unit text not null default 'pieza',
  internal_unit_cost_mxn numeric(14,2) not null default 0,
  sale_unit_price_mxn numeric(14,2) not null default 0,
  internal_total_mxn numeric(14,2) not null default 0,
  sale_total_mxn numeric(14,2) not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'assigned', 'in_progress', 'completed', 'validated', 'cancelled')),
  assigned_contractor_id bigint,
  work_order_id bigint,
  notes text,
  created_at timestamptz not null default now()
);

create unique index if not exists project_operational_item_labor_activities_source_key
  on public.project_operational_item_labor_activities(source_quote_item_labor_activity_id)
  where source_quote_item_labor_activity_id is not null;

create index if not exists project_operational_item_labor_activities_item_id_idx
  on public.project_operational_item_labor_activities(project_operational_item_id);

create index if not exists project_operational_item_labor_activities_activity_id_idx
  on public.project_operational_item_labor_activities(labor_activity_id);

create index if not exists project_operational_item_labor_activities_status_idx
  on public.project_operational_item_labor_activities(status);

alter table public.project_operational_item_labor_activities enable row level security;

drop policy if exists beta_authenticated_select on public.project_operational_item_labor_activities;
drop policy if exists beta_authenticated_insert on public.project_operational_item_labor_activities;
drop policy if exists beta_authenticated_update on public.project_operational_item_labor_activities;
drop policy if exists beta_authenticated_delete on public.project_operational_item_labor_activities;

create policy beta_authenticated_select
on public.project_operational_item_labor_activities
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_operational_item_labor_activities
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_operational_item_labor_activities
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_operational_item_labor_activities
for delete
to authenticated
using (true);
