create table if not exists public.work_orders (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  work_order_number text unique,
  title text not null,
  status text not null default 'draft'
    check (status in ('draft', 'assigned', 'in_progress', 'completed', 'validated', 'cancelled')),
  assigned_to_name text,
  assigned_to_phone text,
  scheduled_start date,
  scheduled_end date,
  notes text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_order_activities (
  id bigint generated by default as identity primary key,
  work_order_id bigint not null references public.work_orders(id) on delete cascade,
  project_operational_item_labor_activity_id bigint references public.project_operational_item_labor_activities(id) on delete set null,
  system_name text,
  product_brand text,
  product_model text,
  product_name text,
  activity_name text,
  quantity_assigned numeric(14,2) not null default 0,
  quantity_completed numeric(14,2) not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'in_progress', 'completed', 'validated', 'cancelled')),
  completion_notes text,
  evidence_photo_url text,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists work_orders_project_id_idx
  on public.work_orders(client_project_id);

create index if not exists work_orders_status_idx
  on public.work_orders(status);

create index if not exists work_order_activities_work_order_id_idx
  on public.work_order_activities(work_order_id);

create index if not exists work_order_activities_operational_activity_id_idx
  on public.work_order_activities(project_operational_item_labor_activity_id);

create index if not exists work_order_activities_status_idx
  on public.work_order_activities(status);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'project_operational_item_labor_activities'
  ) then
    begin
      alter table public.project_operational_item_labor_activities
        add constraint project_operational_item_labor_activities_work_order_id_fkey
        foreign key (work_order_id) references public.work_orders(id) on delete set null;
    exception
      when duplicate_object then null;
    end;
  end if;
end $$;

alter table public.work_orders enable row level security;
alter table public.work_order_activities enable row level security;

drop policy if exists beta_authenticated_select on public.work_orders;
drop policy if exists beta_authenticated_insert on public.work_orders;
drop policy if exists beta_authenticated_update on public.work_orders;
drop policy if exists beta_authenticated_delete on public.work_orders;

create policy beta_authenticated_select
on public.work_orders
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.work_orders
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.work_orders
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.work_orders
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.work_order_activities;
drop policy if exists beta_authenticated_insert on public.work_order_activities;
drop policy if exists beta_authenticated_update on public.work_order_activities;
drop policy if exists beta_authenticated_delete on public.work_order_activities;

create policy beta_authenticated_select
on public.work_order_activities
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.work_order_activities
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.work_order_activities
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.work_order_activities
for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
