create table if not exists public.project_warranties (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  warranty_date date not null default current_date,
  installed_systems text not null,
  equipment_warranty_months integer not null default 12 check (equipment_warranty_months >= 0),
  equipment_warranty_start_date date not null,
  equipment_warranty_end_date date not null,
  installation_warranty_months integer not null default 12 check (installation_warranty_months >= 0),
  installation_warranty_start_date date not null,
  installation_warranty_end_date date not null,
  preventive_maintenance_required boolean not null default false,
  preventive_maintenance_frequency_months integer check (preventive_maintenance_frequency_months is null or preventive_maintenance_frequency_months > 0),
  preventive_maintenance_cost_mxn numeric(14,2) check (preventive_maintenance_cost_mxn is null or preventive_maintenance_cost_mxn >= 0),
  warranty_management_included_until date,
  warranty_management_requires_contract_after boolean not null default true,
  maintenance_policy_active boolean not null default false,
  maintenance_policy_reference text,
  support_email text not null,
  alfa_representative_name text not null,
  status text not null default 'issued' check (status in ('draft', 'issued')),
  pdf_url text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_warranties_project_id_idx
  on public.project_warranties(client_project_id);

create index if not exists project_warranties_warranty_date_idx
  on public.project_warranties(warranty_date);

create index if not exists project_warranties_status_idx
  on public.project_warranties(status);

create index if not exists project_warranties_maintenance_policy_active_idx
  on public.project_warranties(maintenance_policy_active);

create or replace function public.set_project_warranties_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_project_warranties_updated_at
  on public.project_warranties;

create trigger set_project_warranties_updated_at
before update on public.project_warranties
for each row
execute function public.set_project_warranties_updated_at();

alter table public.project_warranties enable row level security;

drop policy if exists beta_authenticated_select on public.project_warranties;
drop policy if exists beta_authenticated_insert on public.project_warranties;
drop policy if exists beta_authenticated_update on public.project_warranties;
drop policy if exists beta_authenticated_delete on public.project_warranties;

create policy beta_authenticated_select
on public.project_warranties
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_warranties
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_warranties
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_warranties
for delete
to authenticated
using (true);
