alter table public.clients
  add column if not exists tax_rfc text,
  add column if not exists tax_business_name text,
  add column if not exists tax_regime text,
  add column if not exists default_cfdi_use text,
  add column if not exists tax_zip_code text,
  add column if not exists billing_email text;

create table if not exists public.project_invoices (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  invoice_date date not null default current_date,
  subtotal_mxn numeric(14,2) not null check (subtotal_mxn >= 0),
  iva_mxn numeric(14,2) not null default 0 check (iva_mxn >= 0),
  total_mxn numeric(14,2) not null check (total_mxn >= 0),
  status text not null default 'draft' check (status in ('draft', 'issued', 'cancelled', 'paid')),
  facturama_id text,
  sat_uuid text,
  xml_url text,
  pdf_url text,
  created_at timestamptz not null default now()
);

alter table public.project_invoices
  add column if not exists client_project_id bigint references public.client_projects(id) on delete cascade,
  add column if not exists client_id bigint references public.clients(id) on delete cascade,
  add column if not exists invoice_date date default current_date,
  add column if not exists subtotal_mxn numeric(14,2),
  add column if not exists iva_mxn numeric(14,2),
  add column if not exists total_mxn numeric(14,2),
  add column if not exists status text default 'draft',
  add column if not exists facturama_id text,
  add column if not exists sat_uuid text,
  add column if not exists xml_url text,
  add column if not exists pdf_url text,
  add column if not exists created_at timestamptz default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'project_invoices'
      and column_name = 'subtotal'
  ) then
    execute 'update public.project_invoices set subtotal_mxn = coalesce(subtotal_mxn, subtotal)';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'project_invoices'
      and column_name = 'iva'
  ) then
    execute 'update public.project_invoices set iva_mxn = coalesce(iva_mxn, iva)';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'project_invoices'
      and column_name = 'total'
  ) then
    execute 'update public.project_invoices set total_mxn = coalesce(total_mxn, total)';
  end if;
end $$;

update public.project_invoices
set
  subtotal_mxn = coalesce(subtotal_mxn, 0),
  iva_mxn = coalesce(iva_mxn, 0),
  total_mxn = coalesce(total_mxn, coalesce(subtotal_mxn, 0) + coalesce(iva_mxn, 0)),
  status = coalesce(status, 'draft'),
  invoice_date = coalesce(invoice_date, current_date),
  created_at = coalesce(created_at, now());

create index if not exists project_invoices_client_project_id_idx
  on public.project_invoices(client_project_id);

create index if not exists project_invoices_client_id_idx
  on public.project_invoices(client_id);

create index if not exists project_invoices_invoice_date_idx
  on public.project_invoices(invoice_date);

create index if not exists project_invoices_status_idx
  on public.project_invoices(status);

create index if not exists project_invoices_facturama_id_idx
  on public.project_invoices(facturama_id);

alter table public.project_invoices enable row level security;

drop policy if exists beta_authenticated_select on public.project_invoices;
drop policy if exists beta_authenticated_insert on public.project_invoices;
drop policy if exists beta_authenticated_update on public.project_invoices;
drop policy if exists beta_authenticated_delete on public.project_invoices;

create policy beta_authenticated_select
on public.project_invoices
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_invoices
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_invoices
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_invoices
for delete
to authenticated
using (true);
