create table if not exists public.project_purchase_lines (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  quote_item_id bigint references public.quote_items(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  supplier text,
  product_brand text,
  product_model text,
  product_name text,
  quantity_required numeric(14,2) not null default 0,
  quantity_purchased numeric(14,2) not null default 0,
  cost_currency text not null default 'USD' check (cost_currency in ('USD', 'MXN')),
  unit_cost numeric(14,2) not null default 0,
  total_required_cost numeric(14,2) not null default 0,
  total_purchased_cost numeric(14,2) not null default 0,
  total_pending_cost numeric(14,2) not null default 0,
  purchase_status text not null default 'pending'
    check (purchase_status in ('pending', 'partial', 'purchased', 'in_warehouse')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_purchase_events (
  id bigint generated by default as identity primary key,
  project_purchase_line_id bigint not null references public.project_purchase_lines(id) on delete cascade,
  purchase_date date not null,
  quantity numeric(14,2) not null check (quantity > 0),
  unit_cost numeric(14,2) not null default 0,
  cost_currency text not null check (cost_currency in ('USD', 'MXN')),
  exchange_rate numeric(14,4),
  supplier text,
  invoice_reference text,
  warehouse_status text not null default 'pending'
    check (warehouse_status in ('pending', 'received', 'delivered_to_site')),
  notes text,
  created_at timestamptz not null default now()
);

alter table public.project_purchase_events
  add column if not exists exchange_rate numeric(14,4);

create unique index if not exists project_purchase_lines_quote_item_id_key
  on public.project_purchase_lines(quote_item_id)
  where quote_item_id is not null;

create index if not exists project_purchase_lines_client_project_id_idx
  on public.project_purchase_lines(client_project_id);

create index if not exists project_purchase_lines_quote_item_id_idx
  on public.project_purchase_lines(quote_item_id);

create index if not exists project_purchase_lines_supplier_idx
  on public.project_purchase_lines(supplier);

create index if not exists project_purchase_lines_status_idx
  on public.project_purchase_lines(purchase_status);

create index if not exists project_purchase_events_line_id_idx
  on public.project_purchase_events(project_purchase_line_id);

alter table public.project_purchase_lines enable row level security;
alter table public.project_purchase_events enable row level security;

drop policy if exists beta_authenticated_select on public.project_purchase_lines;
drop policy if exists beta_authenticated_insert on public.project_purchase_lines;
drop policy if exists beta_authenticated_update on public.project_purchase_lines;
drop policy if exists beta_authenticated_delete on public.project_purchase_lines;

create policy beta_authenticated_select
on public.project_purchase_lines
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_purchase_lines
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_purchase_lines
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_purchase_lines
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.project_purchase_events;
drop policy if exists beta_authenticated_insert on public.project_purchase_events;
drop policy if exists beta_authenticated_update on public.project_purchase_events;
drop policy if exists beta_authenticated_delete on public.project_purchase_events;

create policy beta_authenticated_select
on public.project_purchase_events
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_purchase_events
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_purchase_events
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_purchase_events
for delete
to authenticated
using (true);

-- TODO: Limitar edicion a perfiles admin/pm cuando existan roles operativos formales.
