create table if not exists public.fiscal_document_email_logs (
  id bigint generated by default as identity primary key,
  document_type text not null,
  document_id bigint not null,
  document_uuid text,
  to_email text not null,
  cc_email text,
  subject text not null,
  message text,
  status text not null default 'sent',
  resend_email_id text,
  error_message text,
  sent_by uuid references auth.users(id),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  constraint fiscal_document_email_logs_document_type_check
    check (document_type in ('invoice', 'payment_complement')),
  constraint fiscal_document_email_logs_status_check
    check (status in ('sent', 'failed'))
);

create index if not exists fiscal_document_email_logs_document_idx
  on public.fiscal_document_email_logs(document_type, document_id, created_at desc);

create index if not exists fiscal_document_email_logs_sent_by_idx
  on public.fiscal_document_email_logs(sent_by);

alter table public.fiscal_document_email_logs enable row level security;

drop policy if exists beta_authenticated_select on public.fiscal_document_email_logs;
drop policy if exists beta_authenticated_insert on public.fiscal_document_email_logs;

create policy beta_authenticated_select
on public.fiscal_document_email_logs
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.fiscal_document_email_logs
for insert
to authenticated
with check (true);
