-- El Vigia de ALFA OS - Fase 0: cimientos.
--
-- Crea la infraestructura de la capa autonoma de vigilancia:
--   vigia_sensor_runs   - una fila por corrida de un sensor
--   vigia_findings      - una fila por hallazgo, con deduplicacion por (sensor_id, fingerprint)
--   vigia_audit_log     - bitacora append-only de todo lo que el Vigia ve, propone y ejecuta
--   vigia_v_*           - vistas de deteccion para los primeros sensores (INT-*, CST-*)
--
-- Frentes de la Fase 1: integridad de datos (INT) y costos/margenes (CST).
-- Todo lo escribe el runner con el cliente admin (service_role), que salta RLS.
-- Las vistas y tablas se exponen a 'authenticated' solo para lectura (bandeja futura).
--
-- Aplicado a produccion el 2026-08-30 (migracion supabase "vigia_phase0"). Cambio
-- puramente aditivo: solo crea objetos nuevos (tablas vigia_*, vistas vigia_v_*,
-- policies sobre esas tablas nuevas). No toca ninguna tabla, columna ni RLS
-- existente. Reversible con: drop de las tablas y vistas vigia_*.

-- ---------------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------------

create table if not exists public.vigia_sensor_runs (
  id bigint generated by default as identity primary key,
  sensor_id text not null,
  status text not null default 'running' check (status in ('running', 'ok', 'error')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  findings_count integer not null default 0,
  resolved_count integer not null default 0,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists vigia_sensor_runs_sensor_idx
  on public.vigia_sensor_runs (sensor_id, started_at desc);

create table if not exists public.vigia_findings (
  id bigint generated by default as identity primary key,
  sensor_id text not null,
  fingerprint text not null,
  domain text not null,
  lane text not null check (lane in ('auto_aplicado', 'requiere_autorizacion', 'prestar_atencion')),
  severity text not null default 'medio' check (severity in ('info', 'bajo', 'medio', 'alto', 'critico')),
  confidence text not null default 'media' check (confidence in ('alta', 'media', 'baja')),
  title text not null,
  summary text not null,
  evidence jsonb not null default '{}'::jsonb,
  impact_mxn numeric(16,2),
  entity_type text,
  entity_id text,
  proposed_action jsonb,
  status text not null default 'abierto'
    check (status in ('abierto', 'reconocido', 'descartado', 'resuelto', 'auto_aplicado', 'expirado')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1,
  resolved_at timestamptz,
  decided_by text,
  decided_at timestamptz,
  decision_note text,
  run_id bigint references public.vigia_sensor_runs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (sensor_id, fingerprint)
);

create index if not exists vigia_findings_status_idx on public.vigia_findings (status);
create index if not exists vigia_findings_domain_idx on public.vigia_findings (domain);
create index if not exists vigia_findings_lane_idx on public.vigia_findings (lane);
create index if not exists vigia_findings_last_seen_idx on public.vigia_findings (last_seen_at desc);
create index if not exists vigia_findings_entity_idx on public.vigia_findings (entity_type, entity_id);

create table if not exists public.vigia_audit_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor text not null default 'vigia',
  sensor_id text,
  finding_id bigint references public.vigia_findings(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vigia_audit_log_created_idx on public.vigia_audit_log (created_at desc);
create index if not exists vigia_audit_log_finding_idx on public.vigia_audit_log (finding_id);

-- ---------------------------------------------------------------------------
-- RLS: lectura para usuarios internos autenticados; escritura solo service_role
-- ---------------------------------------------------------------------------

alter table public.vigia_sensor_runs enable row level security;
alter table public.vigia_findings enable row level security;
alter table public.vigia_audit_log enable row level security;

drop policy if exists vigia_authenticated_select on public.vigia_sensor_runs;
create policy vigia_authenticated_select on public.vigia_sensor_runs
  for select to authenticated using (true);

drop policy if exists vigia_authenticated_select on public.vigia_findings;
create policy vigia_authenticated_select on public.vigia_findings
  for select to authenticated using (true);

drop policy if exists vigia_authenticated_select on public.vigia_audit_log;
create policy vigia_authenticated_select on public.vigia_audit_log
  for select to authenticated using (true);

-- ---------------------------------------------------------------------------
-- Vistas de deteccion
-- ---------------------------------------------------------------------------

-- INT-01 - Partidas operativas duplicadas
create or replace view public.vigia_v_int01_duplicate_operational_items as
with active_ops as (
  select * from public.project_operational_items where status <> 'deleted'
),
approved_projects as (
  select distinct client_project_id
  from public.quotes
  where status = 'approved' and client_project_id is not null
)
select
  o.client_project_id,
  o.product_id,
  o.source_quote_item_id,
  count(*) as active_count,
  array_agg(o.id order by o.id) as operational_item_ids,
  min(o.product_brand) as product_brand,
  min(o.product_model) as product_model,
  'colision_quote_item' as pattern
from active_ops o
where o.source_quote_item_id is not null
group by o.client_project_id, o.product_id, o.source_quote_item_id
having count(*) > 1
union all
select
  o.client_project_id,
  o.product_id,
  null::bigint as source_quote_item_id,
  count(*) as active_count,
  array_agg(o.id order by o.id) as operational_item_ids,
  min(o.product_brand) as product_brand,
  min(o.product_model) as product_model,
  'huerfana_sin_vinculo' as pattern
from active_ops o
join approved_projects ap on ap.client_project_id = o.client_project_id
where o.change_origin = 'quote_seed'
  and o.source_quote_item_id is null
  and exists (
    select 1 from active_ops s
    where s.client_project_id = o.client_project_id
      and s.product_id = o.product_id
      and s.source_quote_item_id is not null
  )
group by o.client_project_id, o.product_id;

-- INT-02 - Lineas de compra huerfanas con historial de compras
create or replace view public.vigia_v_int02_orphan_purchase_lines as
select
  l.id as line_id,
  l.client_project_id,
  l.product_id,
  l.product_brand,
  l.product_model,
  l.quantity_required,
  l.quantity_purchased,
  l.total_purchased_cost,
  (select count(*) from public.project_purchase_events e
     where e.project_purchase_line_id = l.id) as event_count,
  (select count(*) from public.project_purchase_lines s
     join public.project_operational_items a2 on a2.id = s.project_operational_item_id
    where s.client_project_id = l.client_project_id
      and s.product_id is not distinct from l.product_id
      and a2.status <> 'deleted'
      and s.id <> l.id) as healthy_sibling_count
from public.project_purchase_lines l
left join public.project_operational_items a on a.id = l.project_operational_item_id
where (l.project_operational_item_id is null or a.status = 'deleted')
  and coalesce(l.quantity_purchased, 0) > 0;

-- INT-03 - Partidas operativas de una version de cotizacion ya superada
create or replace view public.vigia_v_int03_stale_version_operational_items as
select
  o.client_project_id,
  o.source_quote_id,
  q.version as quote_version,
  count(*) as operational_item_count,
  array_agg(o.id order by o.id) as operational_item_ids
from public.project_operational_items o
join public.quotes q on q.id = o.source_quote_id
where o.status <> 'deleted'
  and o.change_origin = 'quote_seed'
  and coalesce(q.is_latest, true) = false
  and exists (
    select 1 from public.quotes q2
    where q2.client_project_id = q.client_project_id
      and coalesce(q2.is_latest, false) = true
      and q2.status = 'approved'
  )
group by o.client_project_id, o.source_quote_id, q.version;

-- INT-04 - Las lineas de compra piden mas que la base operativa activa
--          (por producto y proyecto). La base operativa ya incorpora adiciones
--          de traduccion y multiples cotizaciones aprobadas, asi que un exceso
--          aqui es senal real, no ruido de alcance.
create or replace view public.vigia_v_int04_purchase_over_operational as
with op_qty as (
  select client_project_id, product_id, sum(quantity) as op_qty
  from public.project_operational_items
  where status <> 'deleted' and product_id is not null
  group by client_project_id, product_id
),
pl_qty as (
  select client_project_id, product_id,
         sum(quantity_required) as pl_qty,
         sum(quantity_purchased) as pl_purchased
  from public.project_purchase_lines
  where product_id is not null
  group by client_project_id, product_id
)
select
  p.client_project_id,
  p.product_id,
  coalesce(o.op_qty, 0) as op_qty,
  p.pl_qty,
  p.pl_purchased,
  p.pl_qty - coalesce(o.op_qty, 0) as diff
from pl_qty p
left join op_qty o
  on o.client_project_id = p.client_project_id and o.product_id = p.product_id
where p.pl_qty > coalesce(o.op_qty, 0)
  and p.pl_qty - coalesce(o.op_qty, 0) >= 1;

-- CST-01 - Sobrecosto real de compra vs estimado operativo
create or replace view public.vigia_v_cst01_purchase_overrun as
select
  e.id as event_id,
  e.project_purchase_line_id as line_id,
  l.client_project_id,
  l.product_id,
  l.product_brand,
  l.product_model,
  e.purchase_date,
  e.quantity,
  e.unit_cost,
  e.cost_currency,
  e.exchange_rate,
  case when upper(coalesce(e.cost_currency, 'USD')) = 'USD'
       then e.unit_cost * coalesce(nullif(e.exchange_rate, 0), 0)
       else e.unit_cost end as real_unit_mxn,
  case when upper(coalesce(o.cost_currency, 'USD')) = 'USD'
       then coalesce(o.operational_unit_cost, 0) * coalesce(nullif(o.exchange_rate, 0), 0)
       else coalesce(o.operational_unit_cost, 0) end as est_unit_mxn
from public.project_purchase_events e
join public.project_purchase_lines l on l.id = e.project_purchase_line_id
join public.project_operational_items o on o.id = l.project_operational_item_id
where coalesce(e.quantity, 0) > 0;

-- CST-02 - Costo de proveedor sin actualizar en un producto que esta por comprarse
--          o alimenta el margen de una cotizacion aprobada vigente.
--          Alcance deliberadamente estrecho: solo dispara cuando el costo rancio
--          esta a punto de afectar dinero. Se afloja el intervalo si hace falta.
create or replace view public.vigia_v_cst02_stale_supplier_cost as
with stale as (
  select id, brand, model, name, supplier, cost_price, cost_currency, cost_updated_at
  from public.products
  where is_active = true
    and coalesce(cost_price, 0) > 0
    and (cost_updated_at is null or cost_updated_at < now() - interval '120 days')
),
in_approved_latest as (
  select distinct qi.product_id
  from public.quote_items qi
  join public.quotes q on q.id = qi.quote_id
  join public.client_projects cp on cp.id = q.client_project_id
  where q.status = 'approved'
    and coalesce(q.is_latest, false) = true
    and cp.sales_stage in ('won', 'delivered')
),
in_pending_purchase as (
  select distinct l.product_id
  from public.project_purchase_lines l
  join public.client_projects cp on cp.id = l.client_project_id
  where cp.sales_stage in ('won', 'delivered')
    and coalesce(l.quantity_purchased, 0) < l.quantity_required
)
select
  s.id as product_id,
  s.brand,
  s.model,
  s.name,
  s.supplier,
  s.cost_price,
  s.cost_currency,
  s.cost_updated_at,
  (s.id in (select product_id from in_approved_latest)) as in_approved_quote,
  (s.id in (select product_id from in_pending_purchase)) as in_pending_purchase
from stale s
where s.id in (select product_id from in_approved_latest)
   or s.id in (select product_id from in_pending_purchase);

-- CST-03 - Deriva entre el TC cotizado y el TC real al que se compro
create or replace view public.vigia_v_cst03_fx_drift as
with quote_fx as (
  select client_project_id, max(exchange_rate) as quote_fx
  from public.quotes
  where status = 'approved' and coalesce(is_latest, false) = true and coalesce(exchange_rate, 0) > 0
  group by client_project_id
),
real_fx as (
  select
    l.client_project_id,
    sum(e.quantity * e.unit_cost * e.exchange_rate) / nullif(sum(e.quantity * e.unit_cost), 0) as real_fx,
    sum(e.quantity * e.unit_cost) as usd_base
  from public.project_purchase_events e
  join public.project_purchase_lines l on l.id = e.project_purchase_line_id
  where upper(coalesce(e.cost_currency, 'USD')) = 'USD' and coalesce(e.exchange_rate, 0) > 0
  group by l.client_project_id
)
select
  q.client_project_id,
  q.quote_fx,
  r.real_fx,
  r.usd_base,
  r.real_fx - q.quote_fx as fx_diff,
  (r.real_fx - q.quote_fx) / q.quote_fx as fx_diff_pct
from quote_fx q
join real_fx r on r.client_project_id = q.client_project_id
where abs((r.real_fx - q.quote_fx) / q.quote_fx) > 0.05;

-- ---------------------------------------------------------------------------
notify pgrst, 'reload schema';
