alter table public.service_reports
  add column if not exists recommendations text,
  add column if not exists completed_at timestamptz,
  add column if not exists service_email_sent_at timestamptz,
  add column if not exists service_email_sent_to text,
  add column if not exists service_email_status text,
  add column if not exists service_email_error text;

do $$
begin
  alter table public.service_reports
    drop constraint if exists service_reports_status_check;

  alter table public.service_reports
    add constraint service_reports_status_check
    check (status in ('draft', 'pending', 'in_progress', 'completed', 'cancelled'));

  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_reports_email_status_check'
  ) then
    alter table public.service_reports
      add constraint service_reports_email_status_check
      check (
        service_email_status is null
        or service_email_status in ('sent', 'error')
      );
  end if;
end $$;

create table if not exists public.service_report_email_history (
  id bigint generated by default as identity primary key,
  service_report_id bigint not null references public.service_reports(id) on delete cascade,
  sent_to text not null,
  cc text,
  subject text not null,
  body_html text not null,
  attachment_names text[] not null default '{}',
  status text not null check (status in ('sent', 'error', 'skipped')),
  error_message text,
  resend_response jsonb,
  sent_at timestamptz not null default now(),
  created_by_user_id uuid references auth.users(id)
);

alter table public.service_report_email_history
  add column if not exists attachment_names text[] not null default '{}';

create index if not exists service_report_email_history_report_id_idx
  on public.service_report_email_history(service_report_id);

create index if not exists service_report_email_history_sent_at_idx
  on public.service_report_email_history(sent_at);

create index if not exists service_reports_completed_at_idx
  on public.service_reports(completed_at);

alter table public.service_report_email_history enable row level security;

drop policy if exists beta_authenticated_select on public.service_report_email_history;
drop policy if exists beta_authenticated_insert on public.service_report_email_history;
drop policy if exists beta_authenticated_update on public.service_report_email_history;
drop policy if exists beta_authenticated_delete on public.service_report_email_history;

create policy beta_authenticated_select
on public.service_report_email_history
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.service_report_email_history
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.service_report_email_history
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.service_report_email_history
for delete
to authenticated
using (true);
