-- Sprint G3 - Plantillas / paquetes estandar de cotizacion
--
-- Una plantilla es un conjunto de lineas (productos + mano de obra con cantidad)
-- para un escenario repetido ("CCTV residencial 4 camaras", "Control acceso 1
-- puerta"). Al usarla: elegir cliente + ajustar cantidades -> se llama a
-- lib/quotes/draftBuilder.ts y se crea un borrador.
--
-- ALFA siempre cotiza a precio de catalogo del producto, asi que las lineas no
-- guardan margen: el precio sale de products.calculated_sale_price al crear el
-- borrador.
--
-- Aditivo: 2 tablas nuevas + RLS select-only. No toca nada existente.

create table if not exists public.quote_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  scenario text,
  default_notes text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_template_lines (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.quote_templates(id) on delete cascade,
  kind text not null check (kind in ('product', 'labor')),
  -- Ref opcional a nivel de esquema para tolerar borrados; la validacion de que
  -- exista se hace en la capa de aplicacion al guardar la plantilla.
  product_id bigint references public.products(id) on delete set null,
  labor_activity_id bigint references public.labor_activity_catalog(id) on delete set null,
  quantity numeric not null default 1 check (quantity > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists quote_template_lines_template_idx
  on public.quote_template_lines (template_id, sort_order);

alter table public.quote_templates enable row level security;
alter table public.quote_template_lines enable row level security;

drop policy if exists quote_templates_authenticated_select on public.quote_templates;
create policy quote_templates_authenticated_select on public.quote_templates
  for select to authenticated using (true);

drop policy if exists quote_template_lines_authenticated_select on public.quote_template_lines;
create policy quote_template_lines_authenticated_select on public.quote_template_lines
  for select to authenticated using (true);

notify pgrst, 'reload schema';
