-- ==============================================================================
-- Migración: Portal de Subcontratistas / Técnicos y Asignación en Servicios
-- Fecha: 2026-08-25
-- ==============================================================================

-- 1. Tabla para usuarios del portal de subcontratistas
create table if not exists public.contractor_portal_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  is_active boolean not null default true,
  invited_at timestamptz,
  invitation_status text not null default 'pending'
    check (invitation_status in ('pending', 'sent', 'existing_user', 'error')),
  invitation_error text,
  created_at timestamptz not null default now(),
  constraint contractor_portal_users_user_id_contractor_id_key unique (user_id, contractor_id)
);

-- Índices de consulta rápida
create index if not exists contractor_portal_users_user_id_idx
  on public.contractor_portal_users(user_id);

create index if not exists contractor_portal_users_contractor_id_idx
  on public.contractor_portal_users(contractor_id);

create index if not exists contractor_portal_users_is_active_idx
  on public.contractor_portal_users(is_active);

-- 2. Columna contractor_id en service_reports para vinculación directa
do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'service_reports'
  ) then
    alter table public.service_reports
      add column if not exists contractor_id bigint references public.contractors(id) on delete set null;

    create index if not exists service_reports_contractor_id_idx
      on public.service_reports(contractor_id);
  end if;
end $$;

-- 3. Row Level Security (RLS)
alter table public.contractor_portal_users enable row level security;

drop policy if exists contractor_portal_users_select_self on public.contractor_portal_users;
drop policy if exists contractor_portal_users_admin_all on public.contractor_portal_users;

-- El usuario subcontratista puede leer su propio registro
create policy contractor_portal_users_select_self
on public.contractor_portal_users
for select
to authenticated
using (user_id = auth.uid());

-- Políticas beta/authenticated para que administradores gestionen contratistas
create policy contractor_portal_users_admin_all
on public.contractor_portal_users
for all
to authenticated
using (true)
with check (true);

-- Permisos
grant all on table public.contractor_portal_users to authenticated;
grant all on table public.contractor_portal_users to service_role;
grant all on sequence public.contractor_portal_users_id_seq to authenticated;
grant all on sequence public.contractor_portal_users_id_seq to service_role;
