-- El Vigia - Sprint B1: ejecutores de 1 clic con respaldo y reversa.
--
-- Cada vez que un ejecutor aplica una correccion desde la Bandeja, guarda aqui
-- un snapshot del estado previo. "Revertir" restaura desde este snapshot.
--
-- Aditivo: tabla nueva. Aplicado a prod 2026-09-01.

create table if not exists public.vigia_action_backups (
  id bigint generated by default as identity primary key,
  finding_id bigint references public.vigia_findings(id) on delete set null,
  action_type text not null,
  actor text not null,
  snapshot jsonb not null,
  summary text,
  applied_at timestamptz not null default now(),
  reverted_at timestamptz,
  reverted_by text
);

create index if not exists vigia_action_backups_finding_idx
  on public.vigia_action_backups (finding_id);
create index if not exists vigia_action_backups_active_idx
  on public.vigia_action_backups (applied_at desc)
  where reverted_at is null;

alter table public.vigia_action_backups enable row level security;

drop policy if exists vigia_authenticated_select on public.vigia_action_backups;
create policy vigia_authenticated_select on public.vigia_action_backups
  for select to authenticated using (true);

notify pgrst, 'reload schema';
