-- Descuentos por partida + reglas comerciales por marca.
--
-- Caso que lo origina (2026-10-01): una cotizacion de aliado que combina Sonos
-- (margen 10%: 0% al cliente, 5% al aliado) con Lutron (15% al cliente y 7.5%
-- al aliado). Hasta ahora el descuento al cliente y el del aliado eran un solo %
-- para toda la cotizacion.
--
-- Regla de calculo (opcion A): el % del aliado se aplica sobre el precio que ya
-- trae el descuento al cliente. Ver lib/quoteLineDiscounts.ts.
--
-- Aditivo: columnas nullable en quote_items (null = hereda de la cotizacion o de
-- la regla de marca) y una tabla nueva. No modifica datos existentes.

alter table public.quote_items
  add column if not exists client_discount_percent numeric(8,4),
  add column if not exists partner_discount_percent numeric(8,4),
  add column if not exists client_discount_mxn numeric(14,2) not null default 0,
  add column if not exists partner_discount_mxn numeric(14,2) not null default 0;

alter table public.quote_items
  drop constraint if exists quote_items_client_discount_percent_range,
  add constraint quote_items_client_discount_percent_range
    check (client_discount_percent is null or (client_discount_percent >= 0 and client_discount_percent <= 100)),
  drop constraint if exists quote_items_partner_discount_percent_range,
  add constraint quote_items_partner_discount_percent_range
    check (partner_discount_percent is null or (partner_discount_percent >= 0 and partner_discount_percent <= 100));

create table if not exists public.brand_commercial_rules (
  id bigint generated by default as identity primary key,
  brand text not null,
  -- null = sin tope (aplica el % general de la cotizacion).
  max_client_discount_percent numeric(8,4)
    check (max_client_discount_percent is null or (max_client_discount_percent >= 0 and max_client_discount_percent <= 100)),
  -- null = usa el % de equipo del aliado definido en la cotizacion.
  partner_discount_percent numeric(8,4)
    check (partner_discount_percent is null or (partner_discount_percent >= 0 and partner_discount_percent <= 100)),
  notes text,
  is_active boolean not null default true,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists brand_commercial_rules_brand_key
  on public.brand_commercial_rules (lower(btrim(brand)));

-- Margenes y comisiones: solo personal interno puede leer. Escritura solo por
-- server action (service role) con rol admin/direccion.
alter table public.brand_commercial_rules enable row level security;

drop policy if exists brand_commercial_rules_internal_select on public.brand_commercial_rules;
create policy brand_commercial_rules_internal_select on public.brand_commercial_rules
  for select to authenticated using (public.is_internal_user());

-- revoke all: los default privileges dan TRUNCATE a authenticated, y TRUNCATE
-- no pasa por RLS.
revoke all on public.brand_commercial_rules from anon, authenticated;
grant select on public.brand_commercial_rules to authenticated;

insert into public.brand_commercial_rules (brand, max_client_discount_percent, partner_discount_percent, notes)
values
  ('Sonos', 0, 5, 'Margen de canal 10%: sin descuento al cliente, se comparte 5/5 con el aliado.')
on conflict do nothing;
-- Lutron no lleva regla fija: el 15% cliente / 7.5% aliado es de un trato
-- puntual y se captura por partida ("aplicar a la marca") en la cotizacion.

notify pgrst, 'reload schema';
