alter table public.clients
  add column if not exists tax_rfc text,
  add column if not exists tax_business_name text,
  add column if not exists tax_regime text,
  add column if not exists default_cfdi_use text,
  add column if not exists tax_zip_code text;

create table if not exists public.project_invoices (
  id bigint generated by default as identity primary key,
  internal_folio text not null unique,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  invoice_date date not null default current_date,
  subtotal numeric(14,2) not null check (subtotal >= 0),
  iva numeric(14,2) not null default 0 check (iva >= 0),
  total numeric(14,2) not null check (total >= 0),
  currency text not null default 'MXN' check (currency in ('MXN', 'USD')),
  status text not null default 'draft' check (status in ('draft', 'issued', 'cancelled', 'paid')),
  xml_url text,
  pdf_url text,
  sat_uuid text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_invoices_client_project_id_idx
  on public.project_invoices(client_project_id);

create index if not exists project_invoices_client_id_idx
  on public.project_invoices(client_id);

create index if not exists project_invoices_invoice_date_idx
  on public.project_invoices(invoice_date);

create index if not exists project_invoices_status_idx
  on public.project_invoices(status);

alter table public.project_invoices enable row level security;

drop policy if exists beta_authenticated_select on public.project_invoices;
drop policy if exists beta_authenticated_insert on public.project_invoices;
drop policy if exists beta_authenticated_update on public.project_invoices;
drop policy if exists beta_authenticated_delete on public.project_invoices;

create policy beta_authenticated_select
on public.project_invoices
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_invoices
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_invoices
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_invoices
for delete
to authenticated
using (true);
