create table if not exists public.project_material_deliveries (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  delivered_to_name text not null,
  delivered_to_phone text,
  delivered_by_name text,
  delivery_date date not null default current_date,
  notes text,
  evidence_photo_url text not null,
  signature_image_url text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.project_material_delivery_items (
  id bigint generated by default as identity primary key,
  delivery_id bigint not null references public.project_material_deliveries(id) on delete cascade,
  project_purchase_line_id bigint references public.project_purchase_lines(id) on delete set null,
  product_brand text,
  product_model text,
  product_name text,
  quantity_delivered numeric(14,2) not null check (quantity_delivered > 0),
  created_at timestamptz not null default now()
);

create index if not exists project_material_deliveries_project_id_idx
  on public.project_material_deliveries(client_project_id);

create index if not exists project_material_deliveries_delivery_date_idx
  on public.project_material_deliveries(delivery_date);

create index if not exists project_material_delivery_items_delivery_id_idx
  on public.project_material_delivery_items(delivery_id);

create index if not exists project_material_delivery_items_purchase_line_id_idx
  on public.project_material_delivery_items(project_purchase_line_id);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'project_purchase_lines'
  ) then
    alter table public.project_purchase_lines
      drop constraint if exists project_purchase_lines_purchase_status_check;

    alter table public.project_purchase_lines
      add constraint project_purchase_lines_purchase_status_check
      check (purchase_status in (
        'pending',
        'partial',
        'purchased',
        'in_warehouse',
        'delivered_to_site'
      ));
  end if;
end $$;

alter table public.project_material_deliveries enable row level security;
alter table public.project_material_delivery_items enable row level security;

drop policy if exists beta_authenticated_select on public.project_material_deliveries;
drop policy if exists beta_authenticated_insert on public.project_material_deliveries;
drop policy if exists beta_authenticated_update on public.project_material_deliveries;
drop policy if exists beta_authenticated_delete on public.project_material_deliveries;

create policy beta_authenticated_select
on public.project_material_deliveries
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_material_deliveries
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_material_deliveries
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_material_deliveries
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.project_material_delivery_items;
drop policy if exists beta_authenticated_insert on public.project_material_delivery_items;
drop policy if exists beta_authenticated_update on public.project_material_delivery_items;
drop policy if exists beta_authenticated_delete on public.project_material_delivery_items;

create policy beta_authenticated_select
on public.project_material_delivery_items
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_material_delivery_items
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_material_delivery_items
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_material_delivery_items
for delete
to authenticated
using (true);
