create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  customer_type text not null
    check (customer_type in ('residencial', 'comercial', 'corporativo', 'industrial')),
  company text,
  phone text not null,
  service text not null,
  message text,
  interest text,
  budget_range text,
  timeline text,
  source text not null default 'pagina_web_alfa_high_end_services',
  status text not null default 'nuevo'
    check (status in ('nuevo', 'contactado', 'calificado', 'descartado')),
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_status_idx
  on public.leads(status);

create index if not exists leads_created_at_idx
  on public.leads(created_at desc);

alter table public.leads
  add column if not exists interest text;

alter table public.leads
  add column if not exists budget_range text;

alter table public.leads
  add column if not exists timeline text;

alter table public.leads enable row level security;

drop policy if exists beta_authenticated_select on public.leads;
drop policy if exists beta_authenticated_insert on public.leads;
drop policy if exists beta_authenticated_update on public.leads;
drop policy if exists beta_authenticated_delete on public.leads;

create policy beta_authenticated_select
  on public.leads
  for select
  to authenticated
  using (true);

create policy beta_authenticated_insert
  on public.leads
  for insert
  to authenticated
  with check (true);

create policy beta_authenticated_update
  on public.leads
  for update
  to authenticated
  using (true)
  with check (true);

create policy beta_authenticated_delete
  on public.leads
  for delete
  to authenticated
  using (true);
