create table if not exists public.project_operational_items (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  source_quote_id bigint references public.quotes(id) on delete set null,
  source_quote_item_id bigint references public.quote_items(id) on delete set null,
  system_name text,
  product_id bigint references public.products(id) on delete set null,
  product_brand text,
  product_model text,
  product_name text,
  product_image_url text,
  quantity numeric(14,2) not null default 0,
  original_quantity numeric(14,2) not null default 0,
  original_unit_cost numeric(14,2) not null default 0,
  operational_unit_cost numeric(14,2) not null default 0,
  cost_currency text not null default 'USD' check (cost_currency in ('USD', 'MXN')),
  exchange_rate numeric(14,4),
  status text not null default 'active'
    check (status in (
      'draft',
      'active',
      'locked',
      'purchased',
      'partially_purchased',
      'delivered'
    )),
  change_origin text not null default 'quote_seed'
    check (change_origin in (
      'quote_seed',
      'translation',
      'commercial_change',
      'manual'
    )),
  created_by_user_id uuid references auth.users(id),
  updated_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists project_operational_items_source_quote_item_id_key
  on public.project_operational_items(source_quote_item_id)
  where source_quote_item_id is not null;

create index if not exists project_operational_items_client_project_id_idx
  on public.project_operational_items(client_project_id);

create index if not exists project_operational_items_source_quote_id_idx
  on public.project_operational_items(source_quote_id);

create index if not exists project_operational_items_product_id_idx
  on public.project_operational_items(product_id);

create index if not exists project_operational_items_status_idx
  on public.project_operational_items(status);

alter table public.project_operational_items enable row level security;

drop policy if exists beta_authenticated_select on public.project_operational_items;
drop policy if exists beta_authenticated_insert on public.project_operational_items;
drop policy if exists beta_authenticated_update on public.project_operational_items;
drop policy if exists beta_authenticated_delete on public.project_operational_items;

create policy beta_authenticated_select
on public.project_operational_items
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_operational_items
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_operational_items
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_operational_items
for delete
to authenticated
using (true);
