create table if not exists public.project_payments (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  payment_date date not null,
  payment_method text,
  payment_reference text,
  payment_category text not null check (payment_category in ('equipment', 'labor')),
  currency text not null check (currency in ('USD', 'MXN')),
  amount numeric(14,2) not null check (amount >= 0),
  exchange_rate numeric(14,4),
  amount_mxn numeric(14,2),
  notes text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint project_payments_labor_mxn_check
    check (payment_category <> 'labor' or currency = 'MXN'),
  constraint project_payments_usd_exchange_rate_check
    check (currency <> 'USD' or exchange_rate is not null)
);

create index if not exists project_payments_client_project_id_idx
  on public.project_payments(client_project_id);

create index if not exists project_payments_payment_date_idx
  on public.project_payments(payment_date);

alter table public.project_payments enable row level security;

drop policy if exists beta_authenticated_select on public.project_payments;
drop policy if exists beta_authenticated_insert on public.project_payments;
drop policy if exists beta_authenticated_update on public.project_payments;
drop policy if exists beta_authenticated_delete on public.project_payments;

create policy beta_authenticated_select
on public.project_payments
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_payments
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_payments
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_payments
for delete
to authenticated
using (true);
