create table if not exists public.project_deliveries (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  delivery_date date not null default current_date,
  status text not null default 'draft' check (status in ('draft', 'delivered')),
  delivered_to_name text not null,
  delivered_to_role text,
  delivered_by_name text,
  observations text,
  client_signature_image_url text,
  alfa_signature_image_url text,
  pdf_url text,
  created_by_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_delivery_evidences (
  id bigint generated by default as identity primary key,
  project_delivery_id bigint not null references public.project_deliveries(id) on delete cascade,
  file_url text not null,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.project_delivery_pending_items (
  id bigint generated by default as identity primary key,
  project_delivery_id bigint not null references public.project_deliveries(id) on delete cascade,
  description text not null,
  status text not null default 'pending' check (status in ('pending', 'resolved')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.project_deliveries
  add column if not exists delivery_email_sent_at timestamptz,
  add column if not exists delivery_email_sent_to text,
  add column if not exists delivery_email_status text,
  add column if not exists delivery_email_error text;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'project_deliveries_status_check'
  ) then
    alter table public.project_deliveries
      drop constraint project_deliveries_status_check;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'project_deliveries_status_check'
  ) then
    alter table public.project_deliveries
      add constraint project_deliveries_status_check
      check (status in ('draft', 'delivered', 'accepted'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'project_deliveries_email_status_check'
  ) then
    alter table public.project_deliveries
      add constraint project_deliveries_email_status_check
      check (
        delivery_email_status is null
        or delivery_email_status in ('sent', 'error')
      );
  end if;
end $$;

create table if not exists public.project_delivery_systems (
  id bigint generated by default as identity primary key,
  project_delivery_id bigint not null references public.project_deliveries(id) on delete cascade,
  system_name text not null,
  delivered boolean not null default true,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists project_deliveries_project_id_idx
  on public.project_deliveries(client_project_id);

create index if not exists project_deliveries_delivery_date_idx
  on public.project_deliveries(delivery_date);

create index if not exists project_deliveries_status_idx
  on public.project_deliveries(status);

create index if not exists project_delivery_evidences_delivery_id_idx
  on public.project_delivery_evidences(project_delivery_id);

create index if not exists project_delivery_pending_items_delivery_id_idx
  on public.project_delivery_pending_items(project_delivery_id);

create index if not exists project_delivery_systems_delivery_id_idx
  on public.project_delivery_systems(project_delivery_id);

create or replace function public.set_project_deliveries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_project_deliveries_updated_at
  on public.project_deliveries;

create trigger set_project_deliveries_updated_at
before update on public.project_deliveries
for each row
execute function public.set_project_deliveries_updated_at();

alter table public.project_deliveries enable row level security;
alter table public.project_delivery_evidences enable row level security;
alter table public.project_delivery_pending_items enable row level security;
alter table public.project_delivery_systems enable row level security;

drop policy if exists beta_authenticated_select on public.project_deliveries;
drop policy if exists beta_authenticated_insert on public.project_deliveries;
drop policy if exists beta_authenticated_update on public.project_deliveries;
drop policy if exists beta_authenticated_delete on public.project_deliveries;

create policy beta_authenticated_select
on public.project_deliveries
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_deliveries
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_deliveries
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_deliveries
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.project_delivery_evidences;
drop policy if exists beta_authenticated_insert on public.project_delivery_evidences;
drop policy if exists beta_authenticated_update on public.project_delivery_evidences;
drop policy if exists beta_authenticated_delete on public.project_delivery_evidences;

create policy beta_authenticated_select
on public.project_delivery_evidences
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_delivery_evidences
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_delivery_evidences
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_delivery_evidences
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.project_delivery_pending_items;
drop policy if exists beta_authenticated_insert on public.project_delivery_pending_items;
drop policy if exists beta_authenticated_update on public.project_delivery_pending_items;
drop policy if exists beta_authenticated_delete on public.project_delivery_pending_items;

create policy beta_authenticated_select
on public.project_delivery_pending_items
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_delivery_pending_items
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_delivery_pending_items
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_delivery_pending_items
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.project_delivery_systems;
drop policy if exists beta_authenticated_insert on public.project_delivery_systems;
drop policy if exists beta_authenticated_update on public.project_delivery_systems;
drop policy if exists beta_authenticated_delete on public.project_delivery_systems;

create policy beta_authenticated_select
on public.project_delivery_systems
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_delivery_systems
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_delivery_systems
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_delivery_systems
for delete
to authenticated
using (true);
