create table if not exists public.project_site_visits (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  created_by_user_id uuid references auth.users(id),
  visit_date date not null default current_date,
  title text not null,
  general_notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.project_site_visit_notes (
  id bigint generated by default as identity primary key,
  project_site_visit_id bigint not null references public.project_site_visits(id) on delete cascade,
  note_text text not null,
  informed_to text,
  commitment_date date,
  created_at timestamptz not null default now()
);

create index if not exists project_site_visits_client_project_id_idx
  on public.project_site_visits(client_project_id);

create index if not exists project_site_visit_notes_visit_id_idx
  on public.project_site_visit_notes(project_site_visit_id);

alter table public.project_site_visits enable row level security;
alter table public.project_site_visit_notes enable row level security;

drop policy if exists beta_authenticated_select on public.project_site_visits;
drop policy if exists beta_authenticated_insert on public.project_site_visits;
drop policy if exists beta_authenticated_update on public.project_site_visits;
drop policy if exists beta_authenticated_delete on public.project_site_visits;

create policy beta_authenticated_select
on public.project_site_visits
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_site_visits
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_site_visits
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_site_visits
for delete
to authenticated
using (true);

drop policy if exists beta_authenticated_select on public.project_site_visit_notes;
drop policy if exists beta_authenticated_insert on public.project_site_visit_notes;
drop policy if exists beta_authenticated_update on public.project_site_visit_notes;
drop policy if exists beta_authenticated_delete on public.project_site_visit_notes;

create policy beta_authenticated_select
on public.project_site_visit_notes
for select
to authenticated
using (true);

create policy beta_authenticated_insert
on public.project_site_visit_notes
for insert
to authenticated
with check (true);

create policy beta_authenticated_update
on public.project_site_visit_notes
for update
to authenticated
using (true)
with check (true);

create policy beta_authenticated_delete
on public.project_site_visit_notes
for delete
to authenticated
using (true);
