create sequence if not exists public.project_profitability_report_number_seq;

create table if not exists public.project_profitability_reports (
  id bigint generated by default as identity primary key,
  client_project_id bigint not null references public.client_projects(id) on delete cascade,
  report_number text unique,
  generated_at timestamptz not null default now(),
  generated_by_user_id uuid references auth.users(id),
  total_sold_mxn numeric(14,2) not null default 0,
  equipment_purchase_total_mxn numeric(14,2) not null default 0,
  work_orders_total_mxn numeric(14,2) not null default 0,
  other_costs_mxn numeric(14,2) not null default 0,
  operating_profit_mxn numeric(14,2) not null default 0,
  operating_margin_percent numeric(8,4) not null default 0,
  status text not null default 'draft',
  director_email_sent_at timestamptz,
  director_email_sent_to text,
  director_email_status text,
  director_email_error text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.project_profitability_reports
  add column if not exists report_number text,
  add column if not exists generated_at timestamptz default now(),
  add column if not exists generated_by_user_id uuid references auth.users(id),
  add column if not exists total_sold_mxn numeric(14,2) default 0,
  add column if not exists equipment_purchase_total_mxn numeric(14,2) default 0,
  add column if not exists work_orders_total_mxn numeric(14,2) default 0,
  add column if not exists other_costs_mxn numeric(14,2) default 0,
  add column if not exists operating_profit_mxn numeric(14,2) default 0,
  add column if not exists operating_margin_percent numeric(8,4) default 0,
  add column if not exists status text default 'draft',
  add column if not exists director_email_sent_at timestamptz,
  add column if not exists director_email_sent_to text,
  add column if not exists director_email_status text,
  add column if not exists director_email_error text,
  add column if not exists notes text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.project_profitability_reports
set
  report_number = coalesce(report_number, 'RENT-' || lpad(id::text, 5, '0')),
  generated_at = coalesce(generated_at, now()),
  total_sold_mxn = coalesce(total_sold_mxn, 0),
  equipment_purchase_total_mxn = coalesce(equipment_purchase_total_mxn, 0),
  work_orders_total_mxn = coalesce(work_orders_total_mxn, 0),
  other_costs_mxn = coalesce(other_costs_mxn, 0),
  operating_profit_mxn = coalesce(operating_profit_mxn, 0),
  operating_margin_percent = coalesce(operating_margin_percent, 0),
  status = coalesce(status, 'draft'),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now());

alter table public.project_profitability_reports
  alter column report_number set not null,
  alter column generated_at set not null,
  alter column total_sold_mxn set default 0,
  alter column total_sold_mxn set not null,
  alter column equipment_purchase_total_mxn set default 0,
  alter column equipment_purchase_total_mxn set not null,
  alter column work_orders_total_mxn set default 0,
  alter column work_orders_total_mxn set not null,
  alter column other_costs_mxn set default 0,
  alter column other_costs_mxn set not null,
  alter column operating_profit_mxn set default 0,
  alter column operating_profit_mxn set not null,
  alter column operating_margin_percent set default 0,
  alter column operating_margin_percent set not null,
  alter column status set default 'draft',
  alter column status set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

create or replace function public.next_project_profitability_report_number()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  sequence_number bigint;
  candidate text;
begin
  loop
    sequence_number := nextval('public.project_profitability_report_number_seq'::regclass);
    candidate := 'RENT-' || lpad(sequence_number::text, 5, '0');

    if not exists (
      select 1
      from public.project_profitability_reports
      where report_number = candidate
    ) then
      return candidate;
    end if;
  end loop;
end;
$$;

alter table public.project_profitability_reports
  alter column report_number set default public.next_project_profitability_report_number();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'project_profitability_reports_status_check'
  ) then
    alter table public.project_profitability_reports
      add constraint project_profitability_reports_status_check
      check (status in ('draft', 'generated', 'sent'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'project_profitability_reports_director_email_status_check'
  ) then
    alter table public.project_profitability_reports
      add constraint project_profitability_reports_director_email_status_check
      check (
        director_email_status is null
        or director_email_status in ('sent', 'error')
      );
  end if;
end $$;

create index if not exists project_profitability_reports_project_id_idx
  on public.project_profitability_reports(client_project_id);

create index if not exists project_profitability_reports_generated_at_idx
  on public.project_profitability_reports(generated_at);

create index if not exists project_profitability_reports_status_idx
  on public.project_profitability_reports(status);

create or replace function public.set_project_profitability_reports_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_project_profitability_reports_updated_at
  on public.project_profitability_reports;

create trigger set_project_profitability_reports_updated_at
before update on public.project_profitability_reports
for each row
execute function public.set_project_profitability_reports_updated_at();

alter table public.project_profitability_reports enable row level security;

drop policy if exists profitability_reports_select_financial_roles
  on public.project_profitability_reports;
drop policy if exists profitability_reports_insert_financial_roles
  on public.project_profitability_reports;
drop policy if exists profitability_reports_update_financial_roles
  on public.project_profitability_reports;
drop policy if exists profitability_reports_delete_financial_roles
  on public.project_profitability_reports;

create policy profitability_reports_select_financial_roles
on public.project_profitability_reports
for select
to authenticated
using (public.current_profile_role() in ('admin', 'direccion', 'finanzas'));

create policy profitability_reports_insert_financial_roles
on public.project_profitability_reports
for insert
to authenticated
with check (public.current_profile_role() in ('admin', 'direccion', 'finanzas'));

create policy profitability_reports_update_financial_roles
on public.project_profitability_reports
for update
to authenticated
using (public.current_profile_role() in ('admin', 'direccion', 'finanzas'))
with check (public.current_profile_role() in ('admin', 'direccion', 'finanzas'));

create policy profitability_reports_delete_financial_roles
on public.project_profitability_reports
for delete
to authenticated
using (public.current_profile_role() in ('admin', 'direccion'));
